### ISSUE TITLE
Added images; they show as broken links

### ISSUE THREAD

**Issue by aliarsalankazmi** [hemangsk/Gravity#1]
Hi Hemang,

Thanks for your Jekyll theme.

I added images to my blog based on your theme.
When I access my repository from GitHub, the image is available and can be seen in the post via repository, but when I load the HTML version of the post from GitHub pages, the image appears as a broken link.

I am pretty sure I need to add something like this to the base structure
`<img src="{{ site.baseurl }}/path/to/img/myImage.jpg">`
but I am unsure where exactly I need to add this in.

**Comment by hemangsk** [comment]
Hi Ali!  Thanks for getting in touch. 😃  😃  😄 

Images on these links are working fine,
http://aliarsalankazmi.github.io/blog_DA/posts/2016/06/24/vis-bukhari-p1.html
http://aliarsalankazmi.github.io/blog_DA/posts/2014/11/16/tracking-tweets.html

Can you send me the link of the page where they are appearing as broken links so I can figure out what's wrong.

The image tag with site baseurl will go like this in Jekyll

```
<img src= "{{ "/path/to/img/myImage.jpg" | prepend: site.baseurl }}">
```

**Comment by aliarsalankazmi** [comment]
Hi Hemang,

Yes, the links you posted are currently showing images, but I have 'hardcoded' the images here using the following:
`<img src="{{ site.baseurl }}/assets/img/hp_narrators.png">`

I think there is a better, generalised way of adding images in, simply using the markdown:
`![Some text](/assets/img/hp_narrators.png)`

But using the above markdown, the image does not render in HTML, although it displays in markdown preview. See [here](https://github.com/aliarsalankazmi/blog_DA/blob/gh-pages/_posts/2016-06-24-vis-bukhari-p1.markdown)

So I am sure I need to set this up in Liquid somewhere, but as I am new, I don't know exactly where to begin!

Thanks again for the great theme! :+1:

**Comment by hemangsk** [comment]
I am really glad you liked it! 😄 😄 

Hey can you give this one a try,
In markdown.. 

```
![Some text]({{site.url}}{{site.baseurl}}/assets/img/hp_narrators.png)
```

and in config.yml

```
baseurl: "/blog_DA"
url: "http://aliarsalankazmi.github.io" 
```

**Comment by aliarsalankazmi** [comment]
That solves it! Thanks :smiley:

**Comment by desmond75** [comment]
I am creating a portfolio using git-hub static page and i want to display some images of projects completed and finding it difficult to do that.I know the syntax for image display but what i do not seem to get here is where to place image on git-hub and and use the path to display it. syntax for image display

**Comment by hemangsk** [comment]
@desmond75 You can store images on github in your repositories anywhere/inside any folder. For example : If I have the image inside 'images' folder in any of my github repo, then I would do :- 

```
Some Text in my article.

![alt-text]({{site.url}}/images/name-of-my-image.jpg)

Some Text in my article
```

^ This would display your image when you put this in a markdown file in that repo and view the markdown file on the deployment URL.

Let me know if this fixes your issue and feel free to create a new issue in this repo if it doesn't work.
