### ISSUE TITLE
I don't know how to solve the problem

### ISSUE THREAD

**Issue by isRaining** [hemangsk/Gravity#10]
Hello,very like your template.
But I want to change the title,I don't know where is the modification,I hope you can help me,Thank you very much!!!
![Uploading 12345678765432.png…](http://img.blog.csdn.net/20160906193747886)

**Comment by hemangsk** [comment]
@isRaining 
In the root directory, you will find the files called about.md, science.md, download.md
Step 1. Rename them to your desired title name.
Step 2. Inside these files there will be a title property inside front matter of these files, change that property to desired title name.
Step 3 Inside these files there will be a permalink property inside front matter of these files, change that property to desired title name.

That's it ! 👍 

The website's title can be changed by Opening _config.yml file present in the root directory and inside it you will find

```
title: Gravity
email: hemangsk@gmail.com
description: The Liberal Jekyll Theme
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hemang_kumar
github_username:  hemangsk

# Build settings
markdown: kramdown
```

You can change the corresponding values to your desired values. Please feel free to get in touch in case you get stuck anywhere 😄 
Happy Coding!
