### ISSUE TITLE
Markdown Links aren't working properly

### ISSUE THREAD

**Issue by nicpolhamus** [hemangsk/Gravity#11]
Hello, first off wonderful theme. 
Now, I'm trying to link to a site where I've gotten some inspiration from, using Markdown's link sytnax.
But, the link isn't being parsed or interpreted.
I've attached some screen shots so you can see what I am referencing. 

![link](https://cloud.githubusercontent.com/assets/13815614/18408105/63e61c50-76ea-11e6-84e2-581167ca722b.PNG)
![not-implemented-links](https://cloud.githubusercontent.com/assets/13815614/18408104/63e48e76-76ea-11e6-8470-45fbf07d2610.PNG)

**Comment by hemangsk** [comment]
@BagelTheKid Hey I'm really sorry for the late reply, been out of city.  So I guess you solved the issue,  the links are visible are in correct format now on your blog, and btw the posts are wonderful. 👍  👍  👍 
 Please feel free to get in touch if you face any kinda prob with the theme ! 😄  😄 

Happy Coding!
