### ISSUE TITLE
Add general & specific jekyll theme installation instructions in README.md

### ISSUE THREAD

**Issue by hemangsk** [hemangsk/Gravity#12]
This issue is created to get you up and running with Jekyll, the superb static site generator. 
Basically you have to, 

**Step 1**
- Write step by step manual to install a jekyll theme in general.
  - You can find it easily on the jekyll doc site, just convert it into markdown with proper formatting.
  - There is a new way of installing jekyll theme, which is introduced in Jekyll v3.0, you have to create a seperate section and add those instructions too.

**Step 2**
- After creating instruction for general theme installation, write specific instructions to install Gravity as a theme. This should not be as detailed as general, keep it minimal. 

That's it! 
Got Queries? Need help getting started ? Just comment below.

**Comment by Projjol-zz** [comment]
Hey, #27 addresses Step 2. I was wondering if Step 1 is needed at all? It would be useful for newcomers to know how Gravity works, maybe not so much about the Jekyll ecosystem 😃

**Comment by Projjol-zz** [comment]
Hey @hemangsk , #28 would be a better solution taking into consideration that the changes should've been in the README file. I've closed the previous PR that pointed to a new file.

**Comment by hemangsk** [comment]
Fixed in #28
