### ISSUE TITLE
House Cleaning README.md

### ISSUE THREAD

**Issue by hemangsk** [hemangsk/Gravity#13]
Currently the README.md is a bunch of images, remove these 3 images from the README.md
**Image 1**
![alt-tag](https://farm2.staticflickr.com/1674/25549273413_3872aa3b1e_o.png)

**Image 2**
![alt-tag](https://farm2.staticflickr.com/1590/26563924866_ec40fd1ccd_o.png)
**Image 3**
![alt-tag](https://farm2.staticflickr.com/1565/25879042020_03acf3c968_o.png)

And convert the instructions to text (markdown).
Solving this is all about how you can make the most clean and organised conversion.

That's it! 
Got Queries? Need help getting started ? Just comment below.

**Comment by jaimellamasi** [comment]
I could do that!

**Comment by jcardoz** [comment]
@hemangsk Let me try this out 👍

**Comment by aj07** [comment]
please merge #15 and add it to my contribution. Thanks :)

**Comment by hemangsk** [comment]
@jllamasi and @jcardoz Welcome to the Gravity community ! 😄 
Either of you can create the first draft and then you can add improvements to it. You guys can decide who is going to work on the first draft and who is going to add improvement to it.
Also there are a bunch of similar enhancement issues related to README file, it will be great if you can work on it. 
Hope you read the whole task!

**Comment by aj07** [comment]
@hemangsk I have submitted rquest for it. please, merge it

**Comment by hemangsk** [comment]
@aj07 Welcome to Gravity community, I think you didn't read the whole task 😅

**Comment by jcardoz** [comment]
@aj07 Convert into markdown language. I am working on this task. Will submit a PR now.

**Comment by hemangsk** [comment]
@jcardoz Okay sounds great!

**Comment by jcardoz** [comment]
@hemangsk can you check if I am on the right track. I have converted the first image.

**Comment by hemangsk** [comment]
@jcardoz Yeah I just checked..its looking perfect!

**Comment by jcardoz** [comment]
@hemangsk Coolio. Will update once completely done

**Comment by hemangsk** [comment]
Solved by @jcardoz in #19  🎉  🎉
