### ISSUE TITLE
Create 'CMD + Shift + 4 + Space Bar key' screenshots of Gravity

### ISSUE THREAD

**Issue by hemangsk** [hemangsk/Gravity#14]
The ultimate aim will be to create a _m x n_ size grid of screenshots in README.md to showcase of different pages in Gravity and put them inside a folder called _Screenshots_.

Different pages which you can choose are,
- Any post on Gravity
- Main page of Gravity
- About Page
- Category Page

**Comment by maayanktyagi** [comment]
Can i solve this?

**Comment by hemangsk** [comment]
Aur bhai kyal haal chaal 😆 😂   🎉

**Comment by maayanktyagi** [comment]
Gravity is awesome!

**Comment by maayanktyagi** [comment]
As awesome as Pixel!!
