### ISSUE TITLE
Atom/RSS Feed for posts pertaining to specific categories

### ISSUE THREAD

**Issue by aliarsalankazmi** [hemangsk/Gravity#22]
Hi Hemang,

Hope you're keeping well.

I needed to share my RSS feed for posts relating to a category with another website - the objective is to enable the other website to publish my posts at their end too.
I can find my RSS feed here:
http://aliarsalankazmi.github.io/blog_DA/feed

I am unsure, however, if the current feed.xml file with `Gravity` enables segregating posts for certain categories.
If it is possible to achieve this still, could you please guide me?
Thanks.

**Comment by hemangsk** [comment]
Hello Ali 😃  I'm well thanks, hope you are great too! 

You are absolutely right currently the theme doesn't support the category specific feed and it only has the feed.xml provided by jekyll by default. I looked on some references and found that we can create a feed-category.xml file in the root directory of our blog which will create category feed of the category specified. 

So for the category "design",

We can create a 'feed.category.xml' file in the root directory.

And then Insert this content in the feed.category.xml file , 

```
---
---
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>

        <title>{{ site.name | xml_escape }}  Design</title>

               <description>Posts categorized as 'design'</description>

            <link>{{ site.url }}</link>
        <atom:link href="{{ site.url }}/{{ page.path }}" rel="self" type="application/rss+xml" />

            {% for post in site.categories.design %}

                    <item>
                <title>{{ post.title | xml_escape }}</title>
                {% if post.excerpt %}
                    <description>{{ post.excerpt | xml_escape }}</description>
        {% endif %}  
                {% if post.content %}
                    <description>{{ post.content | xml_escape }}</description>
                {% endif %}
                <pubDate>{{ post.date | date_to_rfc822 }}</pubDate>
                <link>{{ site.url }}{{ post.url }}</link>
                <guid isPermaLink="true">{{ site.url }}{{ post.url }}</guid>
            </item>
        {% endfor %}
    </channel>
</rss>
```

See I got a feed like this from this file, 

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>Design</title>
<description>Posts categorized as 'design'</description>
<link>http://yourdomain.com</link>
<atom:link href="http://yourdomain.com/feed.category.xml" rel="self" type="application/rss+xml"/>
<item>
<title>Design Stories : Gravity</title>
<description>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
</description>
<description>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p> <p>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</description>
<pubDate>Wed, 30 Mar 2016 19:45:31 +0530</pubDate>
<link>
http://yourdomain.com/design/science/life/2016/03/30/design-stories.html
</link>
<guid isPermaLink="true">
http://yourdomain.com/design/science/life/2016/03/30/design-stories.html
</guid>
</item>
</channel>
</rss>
```

btw here's the reference that helped , https://github.com/snaptortoise/jekyll-rss-feeds/

I'm quite sure it will work just fine and will enable the category specific feed functionality 🎉  
If there's any kind of issue I am always here to help👍  😄 
Also, Really Great blog Sir 😃

**Comment by aliarsalankazmi** [comment]
Thanks a lot, Hemang! That worked perfectly well!
I'm going to save the reference you shared, to learn more.

About the blog, well I think your design is a very important component of the blog too, so I am thankful for your great, minimal design! :smiley:
You may like to stay tuned to the blog, because there is some much more interesting application of analytics coming ahead :wink:
