### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by davidcaiyou** [hemangsk/Gravity#23]
Hey, buddy
I LOVE this theme! It's so simple, clear and cool.
But, is pagination supported by Gravity?
BTW, here is my page 😄 , http://blog.rodickcai.com/

**Comment by hemangsk** [comment]
Hello buddy :smile: It's really awesome to know you liked the theme. And what a great touch you have given to the theme on your blog..  really amazing site :tada:

Regarding the pagination support, the pagination feature is in this project's bucket list but tbh I don't know how to implement it yet, actually I am still learning Jekyll platform and markdown :smile:  and hopefully I will add that feature very very soon. 

Thanks for your kind words. 
Well you just made my day :tada: :smiley: :smile:

**Comment by hemangsk** [comment]
Also if you'd like to implement the pagination feature in Gravity please go ahead 👍 PRs are most welcome :wink:

**Comment by davidcaiyou** [comment]
@hemangsk sure, I will have a try 🎉

**Comment by harshcrop** [comment]
hey, buddy can we apply using Default pagination generator for Jekyll.???

**Comment by hemangsk** [comment]
@harshcrop  Hello buddy!
I haven't tried with default pagination generator, but I think you can apply and it should work smooth. 😄

**Comment by harshcrop** [comment]
this will help you in issue ??

**Comment by HerrBertling** [comment]
Hey guys!

Found this repo via https://24pullrequests.com, have some time on my hands and could probably help. 

Do you want pagination for the index page listing all posts?
Or do you want to have a link to the next and previous post?

And do you have ideas about how it should look?

Happy to help :)

**Comment by hemangsk** [comment]
@HerrBertling hey! That'd be really awesome.
Pagination for the index page listing all posts and also when a post is clicked, a link to the next and previous post at the bottom of page. 

please let me know if you'd like to work on it 🎉 😄

**Comment by hemangsk** [comment]
@harshcrop I have not tried it yet but I think if you don't want a custom pagination, then adding default paginate generator will do just fine and it will get pagination up and running

**Comment by HerrBertling** [comment]
There you go :tada:
