### ISSUE TITLE
yourdomain.com

### ISSUE THREAD

**Issue by rollonbears234** [hemangsk/Gravity#25]
First off, I love this theme. The issue I am having relates to clicking on the about page or articles page and then when I click the home button, it takes me to your domain.com every time. I even set it to my github url and am getting no luck. I've tried for hours and have gotten nothing butt error page not found pages and your domain. 

Can you help me figure out why the template doesn't return to the homepage like I want it to? 

> you can see my page here https://rollonbears234.github.io

**Comment by hemangsk** [comment]
Hey! really glad that you liked the theme 👍
There was a error in Gravity's header.html in master branch, this is the branch which is used when the repo is a user website repo. 

I have solved the navigation issue in this PR, you just need to merge this with your master branch

https://github.com/rollonbears234/rollonbears234.github.io/pull/1

If there's any other issue, feel free to get in touch 😄 

Cheers & Happy Coding!
