### ISSUE TITLE
Does it support timeline in the archive layout?

### ISSUE THREAD

**Issue by dengshenyu** [hemangsk/Gravity#34]
Hi,

I'm using this for my blog, and I feel grateful for your share.

I just want some kind of timeline in the archive layout, does it support? Such as, categorizing the posts by year.

Thanks.

**Comment by hemangsk** [comment]
Hey thanks for getting in touch, it doesn't have a feature to categorize the posts by year in archive layout, but I think http://stackoverflow.com/a/19104574/5056792 will work as is in Gravity. 
You'll have to paste that code in the .md file with layout: archive 
Please let me know if you face any kind of issue.

**Comment by dengshenyu** [comment]
Thanks for help!

It works, but I think the layout should be "page",  instead of "archive".  Below is my archive.md.  Note that I add a div around the code snippet, because it shows as pre in the result page without the div. Hope it helps who also want to categorize posts by year. 

[archive.md.txt](https://github.com/hemangsk/Gravity/files/785987/archive.md.txt)
