### ISSUE TITLE
post.excerpt  not work in chinese

### ISSUE THREAD

**Issue by PrincessGod** [hemangsk/Gravity#36]
hi, i use jekyll lately, and not familiar with html and css, when i finished my post, i founded that home page show all content not excerpt, there is my blog page [P.G](https://princessgod.github.io/),  i really like Gravity and do not want to change theme, so can you help me fix it? thanks, i will be really appreciate.

**Comment by PrincessGod** [comment]
i have tried some works like add "excerpt_separator" in "_config.yml", but no matter what separator i tried it seems always not useful. T_T

**Comment by hemangsk** [comment]
Hey @PrincessGod, Hemang this side,  glad that you liked Gravity ☺️ 
That excerpt thing surely is a bug, thank you very much for reporting it. 

You know actually I've a univ exam tomorrow, so will it be okay if I look into this matter later tonight or tomorrow?  I'll get it fixed for sure latest by tomorrow! 

Thank you ! 😃

**Comment by PrincessGod** [comment]
@hemangsk  really happy to found your reply when i get up.
By the way,  if i can ask you another stupid question? Why my post in github page are "404 not found",there is my [repo](https://github.com/PrincessGod/PrincessGod.github.io), i just copy Gravity and use GitHub for Windows publish and sync, it work fine when i run in local with jekyll serve. i am totaly a novice at this things, and sorry to bother you again.

**Comment by PrincessGod** [comment]
Of course , later is fine. 
The more important thing is exam.
Good luck and have a good exam results!

**Comment by PrincessGod** [comment]
Just now I have some new info maybe helpful,  excerpt works on new page like my custom page "[Life](https://princessgod.github.io/life/)" below. Gravity is truly beautiful,  isn't it?

**Comment by hemangsk** [comment]
Hey thanks a ton for your good wishes !
So the issue is solved, I've also made PR to your [repo](https://github.com/PrincessGod/PrincessGod.github.io/pull/1). 

You can tinker with ```truncate: 200```, changing 200 to any desired value whichever fits right 😃  👍  👍

**Comment by PrincessGod** [comment]
OK， thank you very much.
