### ISSUE TITLE
How to change font size

### ISSUE THREAD

**Issue by euler16** [hemangsk/Gravity#40]
I find the font style and size a bit too different in the preview page of posts and the posts themselves. I want to customize it ...  how should I go about doing it?

**Comment by euler16** [comment]
Also how can we modify the code rendering  style ... I want to modify it to the way Layon renders code snippets.

by the way great work !!! I really loved Gravity

**Comment by hemangsk** [comment]
Hey @euler16 , font size on preview page of posts is on https://github.com/hemangsk/Gravity/blob/master/css/style.scss#L294 

and for posts themselves is at https://github.com/hemangsk/Gravity/blob/master/css/style.scss#L586 

So you can change the values in em, rem, px to the best settings as  per your choice.

For snippet highlighting you just need to include this syntax.css (can be found at  https://github.com/mojombo/tpw/blob/master/css/syntax.css) in the ``` includes/head.html ``` file of Gravity.

Then you  can write code like,
{% highlight ruby linenos %}
def foo
  puts 'foo'
end
{% endhighlight %}

it'll do the job. feel free to ping me if there's any issue, alright :)

Reference http://jekyllrb.com/docs/templates/#stylesheets-for-syntax-highlighting

**Comment by euler16** [comment]
thanks it worked!!!
