### ISSUE TITLE
Filter homepage posts

### ISSUE THREAD

**Issue by 851tk6** [hemangsk/Gravity#43]
How can I tell the homepage to show only posts from /design/ and /download/ but NOT posts from /science/ ?

**Comment by hemangsk** [comment]
This is code responsible for generating list of pages on homepage
https://github.com/hemangsk/Gravity/blob/master/index.html#L8-L22

On line 8 
```
  {% for post in paginator.posts%}
```
After this you can do

{% if post.categories contains "Design" and post.categories contains "Download" %}

and wrap the lines 9 to 22 inside this if statement with

{% endif %}

**Comment by euler16** [comment]
@hemangsk  could u tell me how to change the headings of these filters?

**Comment by 851tk6** [comment]
Wow, super fast response. Thanks so much. This worked:

`{% if post.categories contains "Design" or post.categories contains "Download" %}`

**Comment by hemangsk** [comment]
great!
