### ISSUE TITLE
blank entries on home page

### ISSUE THREAD

**Issue by sammysghost** [hemangsk/Gravity#45]
i just tried this solution:

https://github.com/hemangsk/Gravity/issues/43

`{% if post.categories contains "Design" or post.categories contains "Download" %}`

which sort of works. i noticed when i add new posts to other categories (eg "Artwork"), it shows up on my home page but as a blank entry. what have i done wrong?

	---
	layout: default
	---

	<div class="home">

	  {% for post in paginator.posts %}
	     {% if post.categories contains "Design" or post.categories contains "Downloads" %}
	  <div class="post postContent">
	    <div class="postTag">
	      {{post.tag}}
	    </div>
	    <div class="postTitle">
	    <a class='postLink' href="http://website.com{{site.baseurl}}{{post.url}}">{{post.title}}</a>
	    </div>
	    <div class="postExt">
	   {{ post.content | strip_html | truncate:275}}
	    </div>
	  </div>
	  {% endif %}
	  {% endfor %}
	  {% if paginator.total_pages > 1 %}
	    <nav class="pagination">
	      {% if paginator.previous_page %}
		<a class="paginationLink" href="http://website.com{{ paginator.previous_page_path | prepend: site.baseurl | replace: '//', '/' }}">&laquo; Prev</a>
	      {% endif %}
	    {% for page in (1..paginator.total_pages) %}
	      {% if page == paginator.page %}
		<em class="paginationLink paginationLinkCurrent">{{ page }}</em>
	      {% elsif page == 1 %}
		<a class="paginationLink" href="/">{{ page }}</a>
	      {% else %}
		<a class="paginationLink" href="{{ site.paginate_path | prepend: site.baseurl | replace: '//', '/' | replace: ':num', page }}/">{{ page }}</a>
	      {% endif %}
	    {% endfor %}

	    {% if paginator.next_page %}
	      <a class="paginationLink" href="{{ paginator.next_page_path | prepend: site.baseurl | replace: '//', '/' }}/">Next &raquo;</a>
	    {% endif %}
	    </nav>
	  {% endif %}
	</div>

**Comment by hemangsk** [comment]
It'd be really great if you can provide a link to webpage if its possible, that'll help figure out quickly 😊

**Comment by sammysghost** [comment]
:/ unfortunately my site isn't online just yet. i plan to purchase the domain later next week. i hoped to have the _site html up and running by then :(. any (general) suggestions?

**Comment by hemangsk** [comment]
np,  I'll definitely try to reproduce the error locally tomorrow and find what's wrong

**Comment by sammysghost** [comment]
thank you very much.

**Comment by sammysghost** [comment]
i thought it would be helpful to you to use some of the .md and .html from my site. when i add to `design` or `downloads` the homepage shows both categories perfectly. but when i add to `artwork`, the homepage kinda disappears...


$ _config.yml 

	# Welcome to Jekyll!
	#
	# This config file is meant for settings that affect your whole blog, values
	# which you are expected to set up once and rarely need to edit after that.
	# For technical reasons, this file is *NOT* reloaded automatically when you use
	# 'jekyll serve'. If you change this file, please restart the server process.

	# Site settings
	title: test

	description: "website.com"
	baseurl: "" # the subpath of your site, e.g. /blog
	url: "http://website.com" # the base hostname & protocol for your site

	permalink: /:title.html
	gems: [kramdown,jekyll-paginate]
	paginate: 15
	timezone: NZ
	liquid:
	  error_mode: warn
	# Build settings
	markdown: kramdown

	exclude: ["jekyll", "rougify", "listen", "scss", "sass-convert", "sass", "safe_yaml", "kramdown", "test"]



$ index.html

	---
	layout: default
	---

	<div class="home">


	  {% for post in paginator.posts %}
	     {% if post.categories contains "design" or post.categories contains "download" %}
	  <div class="post postContent">
	    <div class="postTag">
	      {{post.tag}}
	    </div>
	    <div class="postTitle">
	    <a class='postLink' href="http://website.com{{site.baseurl}}{{post.url}}">{{post.title}}</a>
	    </div>
	    <div class="postExt">
	   {{ post.content | strip_html | truncate:275}}
	    </div>
	  </div>
	  {% endif %}
	  {% endfor %}
	  {% if paginator.total_pages > 1 %}
	    <nav class="pagination">
	      {% if paginator.previous_page %}
		<a class="paginationLink" href="http://website.com{{ paginator.previous_page_path | prepend: site.baseurl | replace: '//', '/' }}">&laquo; Prev</a>
	      {% endif %}
	    {% for page in (1..paginator.total_pages) %}
	      {% if page == paginator.page %}
		<em class="paginationLink paginationLinkCurrent">{{ page }}</em>
	      {% elsif page == 1 %}
		<a class="paginationLink" href="/">{{ page }}</a>
	      {% else %}
		<a class="paginationLink" href="{{ site.paginate_path | prepend: site.baseurl | replace: '//', '/' | replace: ':num', page }}/">{{ page }}</a>
	      {% endif %}
	    {% endfor %}

	    {% if paginator.next_page %}
	      <a class="paginationLink" href="{{ paginator.next_page_path | prepend: site.baseurl | replace: '//', '/' }}/">Next &raquo;</a>
	    {% endif %}
	    </nav>
	  {% endif %}
	</div>




$ _layouts/default.html


	<!DOCTYPE html>
	<html>

	  {% include head.html %}

	  <body>

	    {% include header.html %}

	    <div class="page-content">
	      <div class="wrapper">
		{{ content }}
	      </div>
	    </div>

	    {% include footer.html %}

	  </body>

	</html>




$ _layouts/archive.html


	---
	layout: page
	---


	{% for post in site.posts %}
	{% for cat in post.categories %}
	{% if cat == page.category %}



	<div class="post postContent">
	  <div class="postTitle">
	  <a class='postLink' href="http://website.com{{ post.url }}">{{post.title}}</a>

	  </div>
	  <div class="postExt">
	    {{post.excerpt}}
	  </div>
	</div>
	{% endif %}
	{% endfor %}

	{% endfor %}




$ _layouts/page.html 

	---
	layout: default
	---
	<article class="post">
	  <header class="post-header">
	  </header>
	  {% if page.tagline %}
	  <div class="tagline">
	  <span class="page-title">{{page.title}}</span> <span class="page-tagline"><em>{{page.tagline}}</em></span>
	  </div>
	  {% endif %}
	  <div class="post-content">
	    {{ content }}
	  </div>
	</article>



$ _layouts/artwork.html

	---
	layout: page
	---

	{% for post in site.posts %}
	{% for cat in post.categories %}
	{% if cat == page.category %}
	    {% capture day %}{{ post.date | date: '%m%d%Y' }}{% endcapture %}
	    {% capture nday %}{{ post.next.date | date: '%m%d%Y' }}{% endcapture %}

	    {% if day != nday %}
		<br><p class="artwork-entry-date">[ {{ post.date | date: "%b %-d %Y" }} ]</p>
	    {% endif %}
	    <span class="artwork-entry"><span class="char">//</span> <span class="bracket">[  </span>
		{% if post.author == "one" %}<span class="one">{{ post.author }}</span>{% endif %}
		{% if post.author == "two" %}<span class="two">{{ post.author }}</span>{% endif %}
		{% if post.author == "three" %}<span class="three">{{ post.author }}</span>{% endif %}
		{% if post.author == "four" %}<span class="four">{{ post.author }}</span>{% endif %}
		{% if post.author == "five" %}<span class="five">{{ post.author }}</span>{% endif %}
	    <span class="bracket">  ]</span> <span class="char">></span> </span><a 
	href="http://website.com{{ post.url }}"><span class="title">{{ post.title }}</span></a><br>
	{% endif %}
	{% endfor %}
	{% endfor %}




$  design.md 

	---
	layout: archive
	title: design
	permalink: /design/
	category: design
	---

	<div class="home">
	  {% for post in site.categories.n%}
	  <div class="post postContent">
	    <br>
	    <div class="postTitle">
	    <a class='postLink' href="{{site.url}}{{site.baseurl}}{{post.url}}">{{post.title}}</a>
	    </div><span class="hint">
	    <div class="postExt">
	   {{ post.content | strip_html | truncatewords:75 }}
	    </span></div>
	  </div>
	  {% endfor %}
	</div>


$  download.md 

	---
	layout: archive
	title: download
	permalink: /downloads/
	category: "download"
	---

	<div class="home">


	  {% for post in site.categories.n%}
	  <div class="post postContent">
	    </div>
	    <div class="postDay">
	      {{post.tag}}
	    </div>
	    <br>
	    <div class="postTitle">
	    <a class='postLink' href="{{site.url}}{{site.baseurl}}{{post.url}}">{{post.title}}</a>
	    </div><span class="hint">
	    <div class="postExt">
	   {{ post.content | strip_html | truncatewords:275 }}
	    </span></div>
	  </div>


	  {% endfor %}
	  



	</div>


$ artwork.md 

	---
	layout: artwork
	title: artwork
	permalink: /art/
	category: "artwork"
	---

	<div class="home">


	  {% for post in site.categories.n%}
	  <div class="post postContent">
	    </div>
	    <div class="postDay">
	      {{post.tag}}
	    </div>
	    <br>
	    <div class="postTitle">
	    <a class='postLink' href="{{site.url}}{{site.baseurl}}{{post.url}}">{{post.title}}</a>
	    </div><span class="hint">
	    <div class="postExt">
	   {{ post.content | strip_html | truncatewords:275 }}
	    </span></div>
	  </div>


	  {% endfor %}
	  



	</div>

**Comment by hemangsk** [comment]
@sammysghost I've tried to replicate the issue on this branch https://github.com/hemangsk/Gravity/tree/hemangsk/sg, I've added posts with cateogry artwork and design but they seem to work fine on homepage, can you please see if I'm missing something?

**Comment by sammysghost** [comment]
:( no, it's okay. i appreciate your help thus far. thank you.
