### ISSUE TITLE
You can look at my changes

### ISSUE THREAD

**Issue by Mauladen** [hemangsk/Gravity#48]
As I see you no longer develop this project, so I took it and added a couple of useful things
If you have something to offer you can take a look at them and send me a Pull requests
But the repository itself -> [Gravity by mauladen](https://github.com/Mauladen/Gravity)

**Comment by hemangsk** [comment]
Please don't claim someone's else work. If you want to work on a fork, make a proper fork and then develop, no one's stopping you. But this is clearly **stealing** (Adding 'forked from xyz' in repo description is not a way to fork) and I'm reporting to GitHub about this incident. 

And this repository is being properly maintained and developed. See the date of the latest closed issue, so 'no lonnger develop this project' is a downright false assumption.

**Comment by hemangsk** [comment]
And you even changed the name on License, wow https://github.com/Mauladen/Gravity/commit/441fe0181333ffa5d55297c90ae1033e843357d5/#diff-61e0bdf7e1b43c5c93d9488b22e04170R3

**Comment by Mauladen** [comment]
Yes, I forgot about the moment
I'll fix it now.
I did not want to assign this code to myself

**Comment by hemangsk** [comment]
Please have a look into the GitHub documentation of how a fork is created https://help.github.com/articles/fork-a-repo/

**Comment by Mauladen** [comment]
I fixed the license and now everything is fine, I apologize for what happened, as I mentioned, I did not want to assign the code to myself

Regarding the design of the repository, the documentation is advisory in nature and I do not need to do fork of your project

**Comment by Mauladen** [comment]
I just wanted to share the changes, maybe you like something and you put them into your project
