### ISSUE TITLE
How do you change the order of the pages on the main navigation?

### ISSUE THREAD

**Issue by scraggo** [hemangsk/Gravity#49]
Hi! It seems as if the pages in the main navigation are in alphabetical order. Example:

*Home | About | Contact | Portfolio*

Is there any way to change the order to something specified? Thanks!

**Comment by nickjkarl** [comment]
You can change the order by renaming the base files without changing the rest of their contents.
What I do is prepend a number to each page. In your case if you wanted Portfolio to be second in the list rename the pages: 
- 1Portfolio.md
- 2About.md
- 3Contact.md

Changing the order of Home requires editing header.html, more work is required.

**Comment by scraggo** [comment]
I'm relieved that it was something simple. Thank you!

**Comment by hemangsk** [comment]
:+1: 😃
