### ISSUE TITLE
Create a dark theme for Gravity

### ISSUE THREAD

**Issue by hemangsk** [hemangsk/Gravity#51]
- Should be configurable via config.yml, where users can do

```
dark_theme: true
```
to use the dark theme specific CSS.

- I'm imagining a black background and white text over it with some font adjustments, but completely open to your ideas.

:)

**Comment by qgolsteyn** [comment]
I would be happy to take on this project if it's not taken yet :smile:

**Comment by hemangsk** [comment]
@qgolsteyn Sounds great! :)  👍

**Comment by hemangsk** [comment]
Completed via https://github.com/hemangsk/Gravity/pull/52 🎉  🎉
