### ISSUE TITLE
Website not picking up my latest post

### ISSUE THREAD

**Issue by aliarsalankazmi** [hemangsk/Gravity#54]
Hi Hemang,

I hope you are keeping well - and that you remember me! ;)
I am facing a problem: When I add a new blog post, for some reason the commit and update is all fine, but the new post does not appear on the main page.

Solutions I have tried:  
1. Adding `future: true` to config.yaml
2. Check [feed.xml](http://aliarsalankazmi.github.io/blog_DA/feed.xml) to ensure a build was successful (which it is, but for some reason the new blog post does not appear on the main page)

Thanks so much in advance for your help :)

**Comment by aliarsalankazmi** [comment]
Don't worry, my mistake!

I had some non-UTF 8 characters, as I was quoting some Internet text! *embarrassed*

**Comment by hemangsk** [comment]
Hey Ali,

First off sorry for the delay in response. actually exams were going on.. the trickier ones just ended today 😃   It's always really great to hear from you! I hope you are keeping well too 😊   
Glad the issue got resolved :) 
If any issue/troubleshooting with the theme in future just let me know, will get it fixed right away.  
my email is  hemangsk@gmail.com.
