### ISSUE TITLE
Github page does not exist.

### ISSUE THREAD

**Issue by eddyizm** [hemangsk/Gravity#55]
I forked this to see what it looked like. I changed the link to my user name and am using the gh-pages and it returns a 404. 

I changed it to the master branch after deleting the rest, and the page is missing all the css. What part am I missing? All the other jekyll themes seem to just work off a fork.

**Comment by hemangsk** [comment]
Hey :)

This happened after you fork it and change the url here 
```https://github.com/eddyizm/Gravity/blob/gh-pages/_config.yml ```
to ```eddyizm.github.io```
and ```baseUrl``` is set to /Gravity ?

**Comment by eddyizm** [comment]
I think you are right. I'm new to Jekyll pages and just figured this out on another template I was playing with. Thanks!
