### ISSUE TITLE
How to build up this theme with Github Page?

### ISSUE THREAD

**Issue by zhang-wenjun** [hemangsk/Gravity#60]
I directly fork this repository to my github and build my site. However, the page doesn't look right, with only the raw elements. It seems that the **scss** doesn't work. How could I get those things right? 

My site url is [https://zhang-wenjun.github.io/HomePage_Gravity/](https://zhang-wenjun.github.io/HomePage_Gravity/)

Thank you!

![image](https://user-images.githubusercontent.com/32013526/50553962-c2b57d80-0cec-11e9-954b-c74ffd3c475b.png)

**Comment by hemangsk** [comment]
https://github.com/zhang-wenjun/HomePage_Gravity/blob/master/_config.yml#L13 needs the value baseUrl as HomePage_Gravity and site url should be set zhang-wenjun.github.io

**Comment by zhang-wenjun** [comment]
> https://github.com/zhang-wenjun/HomePage_Gravity/blob/master/_config.yml#L13 needs the value baseUrl as HomePage_Gravity and site url should be set zhang-wenjun.github.io

Thank you so much! It could work now~

**Comment by hemangsk** [comment]
Great :)

**Comment by hemangsk** [comment]
Closing, pls let me know if you face any other issues with this theme.
