### ISSUE TITLE
creating posts

### ISSUE THREAD

**Issue by BT5U** [hemangsk/Gravity#8]
hey i just installed gravity on a brand new server and im not sure how to add posts.

i copied the default.html layout and renamed it test.html. then copied the science.md in the root diretory and renamed it test.md.

```
$ cat test.md
```

```

---
layout: default
title: test
permalink: /test/
tagline: "Humanity is overrated."
category: "test"

---
```

then i created a new post:

```
$ cat _posts/2017-03-30-test.markdown
```

```

---
layout: default
title:  "Science of Gravity"
date:   2017-03-30 19:45:31 +0530
categories: test
author: "Chandler Bing"

---
```

<>test</p>

but the post doesnt appear after restarting the jekyll server. any idea what im doing wrong?

**Comment by BT5U** [comment]
sorry, github totally mangled my message. not sure how to fix it.

**Comment by hemangsk** [comment]
@BT5U There is no need to rename the default.html and science.md file. In order to add new posts all you got to do this is create a new file inside posts folder.

**Comment by hemangsk** [comment]
As you can see the directory structure of jekyll, 
There's the posts folder, that's where new posts go.

![screen shot 2016-08-28 at 1 56 58 am](https://cloud.githubusercontent.com/assets/13018570/18029896/c1175484-6cc2-11e6-9964-7245b66607a3.png)

Please feel free to discuss any further queries 😃  👍
