### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by BT5U** [hemangsk/Gravity#9]
can you help me identify which lines in style.css i need to modify to invert the color theme. everything black to white, everything dark grey to light grey, etc. sorry, im a noob, clearly.

thanks!

**Comment by hemangsk** [comment]
Hi @BT5U  
Sure I'm happy to help figuring it out ! 

Inside the "css" folder, open the file called style.scss and there you'll find, 

```
// Our variables
$base-font-family: "PT Sans", Helvetica, Arial, sans-serif;
$base-font-size:   16px;
$base-font-weight: 400;
$small-font-size:  $base-font-size * 0.875;
$base-line-height: 1.5;

$spacing-unit:     30px;

$text-color:       #111;
$background-color: #fdfdfd;
$brand-color:      #2a7ae2;

$grey-color:       #828282;
$grey-color-light: lighten($grey-color, 40%);
$grey-color-dark:  darken($grey-color, 25%);

// Width of the content area
$content-width:    800px;

$on-palm:          600px;
$on-laptop:        800px;
```

You can change the corresponding colours in front of variables $text-color and $background-color to your desired colours.

For eg:- 

```
$text-color:       #fff;    
$background-color: #000;
```

Please feel free to ask anything if u get stuck 😄 

Happy Coding!

**Comment by hemangsk** [comment]
@BT5U Hope your issue is resolved, closing issue
